name: robo
on: workflow_dispatch
jobs:
  robo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          pwd
          ls -la
          if [ -f "CLIENTE-A-PRAZO/package.json" ]; then cd CLIENTE-A-PRAZO && npm install; else npm install; fi
      - name: Run bot
        run: |
          if [ -f "CLIENTE-A-PRAZO/index.js" ]; then cd CLIENTE-A-PRAZO && node index.js; else node index.js; fi
